"use strict";
exports.REQUEST_TOPICS = "REQUEST_TOPICS";
exports.RECEIVE_TOPICS = "RECEIVE_TOPICS";
exports.REQUEST_TOPIC = "REQUEST_TOPIC";
exports.RECEIVE_TOPIC = "RECEIVE_TOPIC";
exports.REQUEST_USERINFO = "REQUEST_USERINFO";
exports.RECEIVE_USERINFO = "RECEIVE_USERINFO";
